### PR TITLE
Fix that ducking revolver issue

### LINKED ISSUE #970: Bouncy laser and lightning barrels stop the basic reload on revolver body

### PR DESCRIPTION
**Pull request by toberge**
pls merge the other one first....

or just review this as both of them maybe

Outlining the issue in Norwegian:
- skyt nest siste skudd (her er ammo > 1)
- vent lenge nok til at animasjonen må være ferdig (mens anim kjører er ammo fortsatt > 1)
- prøv å skyte siste skudd (her er ammo == 1 og også <= 1)
--> da får du ikke skutt

This ammo <= 1 check did fix the animation issue we had with you being able to trigger fire animation just as the body started reloading, but removing this not-fix meant I had to fix it otherwise. Adjusted animation speed to actually correspond to the animation length, and gave the laser barrel an actual reduction in fire rate, and now things seem to work smoothly.

Closes #970

### CODE REVIEW

**Comment by toberge** [comment]
may have some funky results with ddr + lazur

File: Assets/Scripts/Augment/GunController.cs [hunk 1]
```diff
@@ -81,6 +82,8 @@ public void SetPlayerInput(InputManager input)
 
     private AugmentAnimator barrelAnimator;
 
+    // TODO denne er faktisk ikke i bruk nå siden den ikke blir satt til true lengre.
+    //      -> men hvis du setter den når vi skyter så brekker du spillet
```
Comment (Fueredoriku) [inline Assets/Scripts/Augment/GunController.cs]: Maybe remove it in that case?

File: Assets/Scripts/Augment/GunController.cs [hunk 2]
```diff
@@ -254,6 +277,7 @@ private void FireGun()
 
         try
         {
+            isFiring = true;
```
Comment (Fueredoriku) [inline Assets/Scripts/Augment/GunController.cs]: I suspect something in this block breaks lazur when continously firing with an automatic firemode

**Review by Fueredoriku — CHANGES_REQUESTED** [review]
Very nice to finally fix the revolver!! 😮

Lazur seems really broken now though, using an automatic firemode body like seeker will break the lazur if holding fire contiously. I think this must be fixed before merge

File: Assets/Scripts/Augment/GunController.cs (hunk 2 above)
Comment (toberge) [reply Assets/Scripts/Augment/GunController.cs]: wait shit did I forget to remove that line :skull:

File: Assets/Scripts/Augment/GunController.cs (hunk 1 above)
Comment (toberge) [reply Assets/Scripts/Augment/GunController.cs]: added more to the comment. ideally we'd have a replacement

File: Assets/Scripts/Augment/GunController.cs (hunk 2 above)
Comment (toberge) [reply Assets/Scripts/Augment/GunController.cs]: removed, should work now

File: Assets/Scripts/Augment/GunController.cs (hunk 1 above)
Comment (Fueredoriku) [reply Assets/Scripts/Augment/GunController.cs]: Yeah this seems like something we need to get to the bottom of at some point. My hunch is that there is some animation event firing somewhere that causes the crash

**Review by Fueredoriku — APPROVED** [review]
It works! Lets goooo!

File: Assets/Scripts/Augment/GunController.cs (hunk 1 above)
Comment (toberge) [reply Assets/Scripts/Augment/GunController.cs]: Yeah, I'll actually remove this source of confusion I suppose
