### PR TITLE
Fix phantome dynamites with boombardier + telescope

### LINKED ISSUE #898: Boombardier + telescope zoom phantom dynamites
When zooming with the boom-bardier + telescope, you can see invisible pooled dynamites temporarily for some mysterious reason

### PR DESCRIPTION
**Pull request by Fueredoriku**

### CODE REVIEW

File: Assets/Scripts/Augment/AugmentImplementations/Telescope.cs [hunk 1]
```diff
@@ -39,6 +39,10 @@ void Start()
         playerMovement.ZoomFov = originalZoomFov * 0.3f;
         playerMovement.LookSpeedZoom = overrideZoomSpeed;
 
+        // No zooming allowed on the BOOM-bardier!
+        if (gunController.GetComponentInChildren<DynamiteBarrel>())
```
Comment (toberge) [inline Assets/Scripts/Augment/AugmentImplementations/Telescope.cs]: Not before the zoomfov-setting line?

**Review by toberge — APPROVED** [review]

File: Assets/Scripts/Augment/AugmentImplementations/Telescope.cs (hunk 1 above)
Comment (Fueredoriku) [reply Assets/Scripts/Augment/AugmentImplementations/Telescope.cs]: Could probably move it yeah
