### PR TITLE
Fix and add gun switching, fix bullet fire trails, fix boombardier explosion initialization

### LINKED ISSUE #436: Training grounds bugs
- [x] #775
- [x] #774

### LINKED ISSUE #925: BOOM-bardier crashes game on detonate
Missing component, possibly VFX in explosion.init

### PR DESCRIPTION
**Pull request by Fueredoriku**
- Fix bullet fire trails
- Fix boombardier explosion initialization
- Fix boombardier audiosource not being in the sound effects group
- Fix and add weapon switching to builds!

### CODE REVIEW

File: Assets/Scripts/Augment/AugmentImplementations/AugmentAnimator.cs [hunk 1]
```diff
@@ -13,4 +13,14 @@ public abstract class AugmentAnimator : MonoBehaviour
     public abstract void OnInitialize(GunStats stats);
     public abstract void OnReload(GunStats stats);
     public abstract void OnFire(GunStats stats);
+    public void Subscribe(GunController gun)
+    {
+        gun.onFire += OnFire;
+        gun.onReload += OnReload;
+    }
+    public void Desubscribe(GunController gun)
```
Comment (toberge) [inline Assets/Scripts/Augment/AugmentImplementations/AugmentAnimator.cs]: Unsubscribe please 😔

File: Assets/Scripts/Augment/AugmentImplementations/DynamiteBarrel.cs [hunk 2]
```diff
@@ -1,8 +1,10 @@
+using JetBrains.Annotations;
```
Comment (toberge) [inline Assets/Scripts/Augment/AugmentImplementations/DynamiteBarrel.cs]: um...

File: Assets/Scripts/Augment/GunFactory.cs [hunk 3]
```diff
@@ -66,6 +65,13 @@ public static GameObject InstantiateGun(Item bodyPrefab, Item barrelPrefab, Item
         return gun;
     }
 
+    public static void DesubscribeAnimators(GameObject gun)
```
Comment (toberge) [inline Assets/Scripts/Augment/GunFactory.cs]: unsubscribe 🙃

File: Assets/Scripts/Augment/GunFactory.cs [hunk 4]
```diff
@@ -66,6 +65,13 @@ public static GameObject InstantiateGun(Item bodyPrefab, Item barrelPrefab, Item
...
+    {
+        var firstPersonGunController = gun.GetComponent<GunFactory>().GunController;
+        firstPersonGunController.onFireStart = null;
+        firstPersonGunController.onReload = null;
```
Comment (toberge) [inline Assets/Scripts/Augment/GunFactory.cs:72]: also... couldn't this just as well call the ginormous unsub method inside guncontroller?

**Review by toberge — CHANGES_REQUESTED** [review]
Woah it's possible to switch guns finally :o

however, here are some issues:

- infinite ammo, likely because of the nullrefexception in PinAnimator.OnFire that is *still* around somehow
- boombardier is still permanently removing FOV change on zoom (within the scene)
- swapping out telescope for sth else keeps the low FOW
- crash with trash uplink + fire somehow?
  ```
  Disconnecting connection: connection(0) because handling a message of type Mirror.RpcMessage caused an Exception. This can happen if the other side accidentally (or an attacker intentionally) sent invalid data. Reason: System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Behaviour.set_enabled(UnityEngine.Behaviour,bool)
  at ContinuousDamage.OnDeath (HealthController healthController, System.Single damage, DamageInfo info) [0x00000] in <652787979de64ea69b7bdcb7af381941>:0 
  at HealthController.ActuallyDealDamage (DamageInfo info) [0x00043] in <652787979de64ea69b7bdcb7af381941>:0 
  at HealthController.DealDamage (DamageInfo info) [0x00008] in <652787979de64ea69b7bdcb7af381941>:0 
  at HitboxController.DamageCollider (DamageInfo info) [0x0004a] in <652787979de64ea69b7bdcb7af381941>:0 
  at ExplosionController.DealDamage (UnityEngine.Collider target, PlayerManager sourcePlayer, System.Boolean& shouldBeReturned, System.Single& scaledDamage) [0x000d9] in <652787979de64ea69b7bdcb7af381941>:0 
  at ExplosionController.Explode (PlayerManager sourcePlayer) [0x000ad] in <652787979de64ea69b7bdcb7af381941>:0 
  at SateliteUplink.UserCode_RpcTriggerImpactExplosion__Vector3 (UnityEngine.Vector3 position) [0x00022] in <652787979de64ea69b7bdcb7af381941>:0 
  at SateliteUplink.InvokeUserCode_RpcTriggerImpactExplosion__Vector3 (Mirror.NetworkBehaviour obj, Mirror.NetworkReader reader, Mirror.NetworkConnectionToClient senderConnection) [0x00022] in <652787979de64ea69b7bdcb7af381941>:0 
  (...rpc trace)
  ```
- please make the interact sign visible:
  image

**Comment by toberge** [comment]
We should also make it so that you start with only stock + bullet and unlock other parts as you use them in matches (with a sign that says something about that). This can be done w/o dealing with The Cache yet :)

File: Assets/Scripts/Augment/GunFactory.cs (hunk 4 above)
Comment (Fueredoriku) [reply Assets/Scripts/Augment/GunFactory.cs:72]: This *has* to be done in this scope, unless we refactor the guncontroller to subscribe the delegate in the same way augmentanimators now do. Such a refactor is in fact needed for everything that currently produces exceptions, so we might as well refactor these at the same time

File: Assets/Scripts/Augment/GunFactory.cs (hunk 3 above)
Comment (Fueredoriku) [reply Assets/Scripts/Augment/GunFactory.cs]: Fixed!

File: Assets/Scripts/Augment/AugmentImplementations/AugmentAnimator.cs (hunk 1 above)
Comment (Fueredoriku) [reply Assets/Scripts/Augment/AugmentImplementations/AugmentAnimator.cs]: Fixed

File: Assets/Scripts/Augment/AugmentImplementations/DynamiteBarrel.cs (hunk 2 above)
Comment (Fueredoriku) [reply Assets/Scripts/Augment/AugmentImplementations/DynamiteBarrel.cs]: Removed

File: Assets/Scripts/Augment/GunFactory.cs (hunk 4 above)
Comment (toberge) [reply Assets/Scripts/Augment/GunFactory.cs:72]: Yeah I see :))))))
Seems fine to save that for a future PR (hopefully soon™️)

**Review by toberge — APPROVED** [review]
A bunch of jank left to fix, but I approve of these changes 👍

**Comment by toberge** [comment]
note that the following is left unresolved:
- inf ammo (though now it's not pin animator) which entails refactoring to do subbing/unsubbing properly
- whatever the crash with trash uplink was (I'm unable to reproduce it)
