### PR TITLE
Add yielding to auction, fix specular sign, fix LOD player color in auction

### LINKED ISSUE #229: Yieldable auction
When all players are done bidding, some wanted to yield in order to speed up the process. One could also autimaticaly speed up the timer when noone has more money to bid with

### PR DESCRIPTION
**Pull request by Fueredoriku**
image

### CODE REVIEW

File: Assets/Scripts/Auction/AuctionDriver.cs [hunk 1]
```diff
@@ -115,6 +125,70 @@ private IEnumerator WaitAndStartCameraAnimation()
...
+    {
+        if (yieldingPlayers.Contains(player))
+            return;
+
+        yieldingPlayers.Add(player);
+        OnYieldChange?.Invoke();
+
+
+        if (isAuctionStart && IsAuctionYielded())
+            StartCoroutine(nameof(WaitAndTryAuctionEnd));
```
Comment (toberge) [inline Assets/Scripts/Auction/AuctionDriver.cs:147]: else stop the coroutine! 

currently it will
- wait for 3 seconds before checking if it should stop :skull: 
- show SKPPING IN X after going back to YIELD X/Y when someone leaves, until those 3 seconds have passed

**Review by toberge — APPROVED** [review]
Looks good, other than the coroutine that should be ended!

File: Assets/Scripts/Auction/AuctionDriver.cs (hunk 1 above)
Comment (Fueredoriku) [reply Assets/Scripts/Auction/AuctionDriver.cs:147]: Fixed 👍
