### PR TITLE
Fix zoom and bad delegate subscription execution ordering

### LINKED ISSUE #774: Gun switching does not work in builds

### PR DESCRIPTION
**Pull request by Fueredoriku**

### CODE REVIEW

File: Assets/Scripts/Augment/GunController.cs [hunk 1]
```diff
@@ -105,10 +105,22 @@ public void Initialize()
...
+    }
+
+    public void DeSubscribeDelegates()
+    {
+        onFire = null;
+        onFireEnd = null;
+        onFireNoAmmo = null;
+        onFireStart = null;
+        onInitializeBullet = null;
+        onReload = null;
```
Comment (toberge) [inline Assets/Scripts/Augment/GunController.cs:119]: You're missing onInitializeGun and the delegates on the ProjectileController

File: Assets/Scripts/Augment/GunController.cs [hunk 2]
```diff
@@ -105,10 +105,22 @@ public void Initialize()
 
     private void OnDestroy()
     {
+        DeSubscribeDelegates();
+    }
+
+    public void DeSubscribeDelegates()
```
Comment (toberge) [inline Assets/Scripts/Augment/GunController.cs]: Perhaps replace De with Un 😔

File: Assets/Scripts/Augment/GunController.cs [hunk 3]
```diff
@@ -216,8 +228,11 @@ private void RpcFireWithNoAmmo()
 
     private void FireGun()
     {
+        if (stats == null)
```
Comment (toberge) [inline Assets/Scripts/Augment/GunController.cs:239]: huh, so this was necessary? 🤔

**Review by toberge — APPROVED** [review]
LGTM :)
