### PR TITLE
Fix negative chip count and multibidding AIs

### LINKED ISSUE #698: AI players and extra local players may get negative chips during auction
wth is goin on

### PR DESCRIPTION
**Pull request by toberge**
- Fix negative chip count by ensuring that we _can_ bid in both the command and client RPC
- Fix AIs being able to cash out lots of chips instantly by rewriting their code to only perform bids once per evaluation

Closes #698

### CODE REVIEW

File: Assets/Scripts/Auction/BiddingPlatform.cs [hunk 1]
```diff
@@ -1,4 +1,5 @@
 using Mirror;
+using Org.BouncyCastle.Tls;
```
Comment (Fueredoriku) [inline Assets/Scripts/Auction/BiddingPlatform.cs]: Wuh?

**Review by Fueredoriku — APPROVED** [review]
Nice fix!

File: Assets/Scripts/Auction/BiddingPlatform.cs (hunk 1 above)
Comment (toberge) [reply Assets/Scripts/Auction/BiddingPlatform.cs]: I blame vscode smh
