### PR TITLE
Fix main menu freeze, resolves #822

### LINKED ISSUE #822: Not skipping intro cinematic locks players out of interacting with the menu

### PR DESCRIPTION
**Pull request by Fueredoriku**

### CODE REVIEW

File: Assets/Scripts/Control&Input/PlayerInputManagerController.cs [hunk 1]
```diff
@@ -86,8 +86,9 @@ private void OnPlayerJoined(PlayerInput playerInput)
         var inputManager = playerInput.GetComponent<InputManager>();
         inputManager.PlayerCamera.enabled = false;
         LocalPlayerInputs.Add(inputManager);
+        if (playerInput.currentControlScheme == "MouseAndKeyboard")
+           inputManager.SetMouseAndKeyboard();
```
Comment (toberge) [inline Assets/Scripts/Control&Input/PlayerInputManagerController.cs:90]: Couldn't we just put this check into the Start method for InputManager, since it sits on the playerinput and already accesses it, and thus avoid exposing the m&k bool?

File: Assets/Scripts/Control&Input/InputManager.cs [hunk 2]
```diff
@@ -95,6 +95,11 @@ void OnDestroy()
         RemoveListeners();
     }
 
+    public void SetMouseAndKeyboard()
```
Comment (toberge) [inline Assets/Scripts/Control&Input/InputManager.cs:98]: And besides, I'm not a fan of having setter-like methods without an actual input parameter. If we keep this method (see my other comment), perhaps rename it to `SetAsMouseAndKeyboard` so that its intent is a little more clear.

**Review by toberge — APPROVED** [review]
Looks sensible, I just have an implementation suggestion

File: Assets/Scripts/Control&Input/PlayerInputManagerController.cs (hunk 1 above)
Comment (Fueredoriku) [reply Assets/Scripts/Control&Input/PlayerInputManagerController.cs:90]: Nope, unfortunately due to the script execution order, this will return false as the add player delegate is invoked before input manager start is able to do anything, which is why I do it right before the line below this comment

File: Assets/Scripts/Control&Input/InputManager.cs (hunk 2 above)
Comment (Fueredoriku) [reply Assets/Scripts/Control&Input/InputManager.cs:98]: Yeah same, it is unfortunate that the state has to be updated by an outside class in this case

Comment (toberge) [reply Assets/Scripts/Control&Input/InputManager.cs:98]: This bit isn't that important so I'll just resolve this comment ¯\_(ツ)_/¯
